export default {
  BACKGROUND_COLOR_LIGHT: '#fff',
  PRIMARY_COLOR_LIGHT: '#fff',
  PRIMARY_COLOR: '#232b2b',
  SECONDARY_COLOR: '#A6A6A6',
  BUTTON_BORDER_COLOR: '#e5e5e5',
  BUTTON_BACKGROUND_COLOR: '#fff',
  BUTTON_BORDER_COLOR_ACTIVE: '#d5d5d5',
  BUTTON_BACKGROUND_COLOR_ACTIVE: '#eee',
};
