export default {
  FONT_SIZE_SMALL: 14,
  FONT_SIZE_MEDIUM: 16,
  FONT_SIZE_LARGE: 20,

  BACKGROUND_COLOR: '#f1f1f1',
  BACKGROUND_COLOR_LIGHT: '#fff',
  COLOR_PRIMARY: '#232b2b',
  COLOR_PRIMARY_LIGHT: '#fff',
  COLOR_SECONDARY: '#A6A6A6',
  COLOR_SECONDARY_LIGHT: '#e5e5e5',
  FORM_ELEMENT_COLOR: '#008577',
  BORDER_COLOR_BUTTON: '#e5e5e5',
  BORDER_COLOR_BUTTON_ACTIVE: '#d5d5d5',
  BACKGROUND_COLOR_BUTTON: '#fff',
  BACKGROUND_COLOR_BUTTON_ACTIVE: '#eee',
  GRADIENT_FIRST_COLOR: '#08AEEA',
  GRADIENT_SECOND_COLOR: '#2AF598',

  // animations
  CONE_COLOR: '#FEA500',
  DEFENSE_COLOR: '#AFAFAF',
  DEFENSE_TEXT_COLOR: '#000',
  // OFFENSE BACKGROUND USE GRADIENT
  OFFENSE_TEXT_COLOR: '#fff',
  DISC_TEXT_COLOR: 'black',
  CUT_COLOR: 'green',
  DISC_COLOR: 'white',
  DISC_BORDER: 'black',
};
